---
title: "Day 2 Practice"
format: html
editor: visual
---

Loading the packages I need!

```{r}
library(tidyverse)
library(palmerpenguins)
```
This is what you put into the console when you're setting up github!
usethis::use_git()
^selection the affirmation selection after this one
usegit::use_github()

Finding the slope of example 1!
```{r}
fx <- expression(x^2)
dx_df <- D(fx,"x")
dx_df

x <- 3
eval(expr=dx_df)
```

Finding the slope of example 2!
```{r}
pa <- expression(2* (3*a+2)^4 - 5)
da_dp <- D(pa, "a")
da_dp

a <- 1.2
eval(expr=da_dp)
```


Making another penguin plot!

```{r}
library(tidyverse)
ggplot(data=penguins, aes(x=bill_length_mm,y=bill_depth_mm)) + 
  geom_point(aes(color=species)) +
  labs(title="Palmer Penguins Bill Length vs Bill Depth", x="Bill Length (mm)", y="Bill Depth(mm)")
```
Making a jitter plot with the same data 

```{r}
library(tidyverse)
ggplot(data=penguins, aes(x=species, y=flipper_length_mm)) +
  geom_jitter() + 
  labs(title="Palmer Penguins Species vs Flipper Length", x="Species Name", y="Flipper Length (mm)")
```

